function constraint_marix = constraint_marix(R,q4,q5,q6,xA,zA)
%CONSTRAINT_MARIX
%    CONSTRAINT_MARIX = CONSTRAINT_MARIX(R,Q4,Q5,Q6,XA,ZA)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    14-Dec-2020 05:38:32

t2 = cos(q4);
t3 = cos(q5);
t4 = cos(q6);
t5 = sin(q4);
t6 = sin(q5);
t7 = sin(q6);
t8 = t3.*zA;
t9 = t4.*t6.*xA;
t10 = -t9;
t11 = t8+t10;
constraint_marix = reshape([1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,-R.*t2.*t3,-R.*t3.*t5,t5.*t7.*xA-t2.*t6.*zA-t2.*t3.*t4.*xA,-t2.*t7.*xA-t5.*t6.*zA-t3.*t4.*t5.*xA,R.*t5.*t6,-R.*t2.*t6,-t5.*t11,t2.*t11,-R.*t2,-R.*t5,-t2.*t4.*xA+t3.*t5.*t7.*xA,-t4.*t5.*xA-t2.*t3.*t7.*xA],[4,5]);
